spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  address: ENC(Cl0kkqW55cNhTXyE9Aa+nvWa6+KP9hWk)
  name: local-server

oauth2:
  client:
    registration:
      google:
        redirect-uri: ENC(azUUVbo9jK43xY8vvFNI7R5LP+pwuJqYCDLB9ATlOmLkjXTFLxBiDcz6flhiER+YG17wGYvOLBI=)

      naver:
        redirect-uri: ENC(NcVr07pwAfoiIMSkVJjTSsiw50MOsRziWgLmk7mh9xiq/h2zCqmUvjBJUsv8ANho0/LvOdpQvgM=)

      kakao:
        redirect-uri: ENC(eJoMngsjBD9MXyCxnjrhmn6y5rmOt2niU2rDRR+pxi35iYCctitoF5Pp5ooE7pD3I3NSSd94z0Q=)

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  address: ENC(uuBZVo6SocCn53cfBmfJ6dLqJBdEx8aYV8ro2zGWTeM=)
  name: blue-server

oauth2:
  client:
    registration:
      google:
        redirect-uri: ENC(6JVhhmzYRaADKqo/M7TGxcX7RsZvy+MMiMdFWih6zYkVx3G7/huFN34aCUxFDuc6B4lFrdIKSpZ+jM1rxCqqCg==)

      naver:
        redirect-uri: ENC(3XWLCGegLGGBg/9qn4JCkvyPAOaQWpUZ9Wq+dY6zDWxfGfZkazeRhQJ5fB11p5OWV1zOqZJPKQBxIfvSqqEJnA==)

      kakao:
        redirect-uri: ENC(X+UPA2P4SlP4cxrcJz2mSiuQyUmXdXwaZXTz7mKeN6WKnRwFq+Xma3548o7IsPFHur4LsxsB4w5/aoStiHBQqA==)

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081
  address: ENC(uuBZVo6SocCn53cfBmfJ6dLqJBdEx8aYV8ro2zGWTeM=)
  name: green-server

oauth2:
  client:
    registration:
      google:
        redirect-uri: ENC(6JVhhmzYRaADKqo/M7TGxcX7RsZvy+MMiMdFWih6zYkVx3G7/huFN34aCUxFDuc6B4lFrdIKSpZ+jM1rxCqqCg==)

      naver:
        redirect-uri: ENC(3XWLCGegLGGBg/9qn4JCkvyPAOaQWpUZ9Wq+dY6zDWxfGfZkazeRhQJ5fB11p5OWV1zOqZJPKQBxIfvSqqEJnA==)

      kakao:
        redirect-uri: ENC(X+UPA2P4SlP4cxrcJz2mSiuQyUmXdXwaZXTz7mKeN6WKnRwFq+Xma3548o7IsPFHur4LsxsB4w5/aoStiHBQqA==)

---

spring:
  config:
    activate:
      on-profile: common

  application:
    name: 'MSG'

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  output:
    ansi:
      enabled: always

springdoc:
  swagger-ui:
    doc-expansion: none

logging:
  level:
    root: info
    com.ssafy.msg: debug
      
header:
  authorization: 'Authorization'