spring:
  datasource:
    #    development
    #    jdbc-url: ENC(vIzCyDVLZQuIg59BhXM854wv0ddCt/iNbqRHQafFSCC1QESkt4gajZdfrLwUZGz1)
    #    username: ENC(fnkZzl1wC8BdtdVjncsorw==)
    #    password: ENC(k2+MVCmCfJ0jlBqKGkxfhg==)

    #    production
    jdbc-url: ENC(DtLstgxX7vb7RTEgJJavOL4olUvXJgsl7c7meXmQ4a2QEHQuFQ1/qUbR4R/oAKv6)
    username: ENC(xSshffkTINFdSKx5rKkKWiZFoGd7JWvc)
    password: ENC(2hcpUHBJxFU/nVcdXxOeLN4seEiGvRp9zfAc0BsZ1TWlx5almOWRVw==)

    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connectionTimeout: 5000
      validationTimeout: 1000
      maximumPoolSize: 10

  data:
    mongodb:
      #      development
      #      uri: ENC(QRdPVFDE6WJUMaQ4X8wlnV3KLT1iL5p3t1VN8nHxoCce0uZk5pd0Sg==)

      #      production
      host: ENC(kuNwa0HYrWNXigVI4FfXETp00QcpDhtW)
      port: ENC(DoQFGqoRFbX2SJkH4l2fxQ==)
      database: ENC(EaC4yYRnGt5mZm6tdW1QWw==)
      username: ENC(vXjqjb5sDU44f8mFf5O94QxlA8Eby1aB)
      password: ENC(5yVg2wrjyUShkEZmt90gQBU8hH5gkDUSOO7O0a/gFxzaA0nsQIvqPQ==)

    redis:
      #      development
      host: ENC(zRyLsnbAU13uKMIyfGbzl8ymxcJy4ml0)
      port: ENC(M8D7oJuhou94vFzDy1KefA==)
      password: ENC(9vr2ooqCRC1USNBtFBipJ+Iu1RCPANsKR4yZ2IVV5EczWoK8A/VrxA==)

      #      production
      #      host: ENC(Sb/Um1a8+nR3XD3JqqxfiIowAgR7MBz2wWDbR4EXjeU=)
      #      port: ENC(ZeD1XKOM1q94GxVLxYBxxA==)
      #      password: ENC(DuXAck3VbANCfOq1PEWEYDx6Q6RuSTrKGA0gSEgcYoesDlrWO2RHJA==)

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(hXs5LlfCOigzQIQ5Z3Lkq627WLxBu2/wOF0ULAwH89zmSl7FUBPyLA==)
    password: ENC(FXwgBwToqerHmqkyCzmUhkbr6GHXMCZiWCyslFIaLzA=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

oauth2:
  client:
    registration:
      google:
        client-id: ENC(S2ZtanY1jB3c8/ap5dBE4Ne6siueJgpPOx375LQvXcC+roATNlgga2BqJUx67w0DJq9rGjSQe2/ETzNNHGeGp9Tqq3fHJzUbsa0N/KC+eRjAMjzFBG4hRw==)
        client-secret: ENC(CMP6rIybeFfWTKLVqV5KXHqkhJdqWS51BndjFpOoI0ziIzipxeAdMEpR9Hi6MNG9)
        authorization-grant-type: authorization_code
        scope: profile, email
        client-name: Google

      naver:
        client-id: ENC(BwZDtXzR3dWPaJXl1v3+GHxrn7wOYpHgHp/OiIJG2iw=)
        client-secret: ENC(Nwmxhq3rFyp+bc7blQQJnhYrewfqE2wc)
        authorization-grant-type: authorization_code
        scope: name, email
        client-name: Naver

      kakao:
        client-id: ENC(aWCA1C06uUHwDgy0VpTsjGzpw9O9ifGfhlxUWH0GTnzOGXpUWPAkw3AXx4VzANIZ)
        client-secret: ENC(Z5mMbHd4OFMjlcgPfIvpRVNvp/2TJcwmVGO4DEgaKLWTGqzUMhVTl7Ib0NA4MYog)
        client-authentication-method: POST
        authorization-grant-type: authorization_code
        scope: profile_nickname, account_email
        client-name: Kakao

    provider:
      google:
        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
        token-uri: https://www.googleapis.com/oauth2/v4/token
        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
        user-name-attribute: sub

      naver:
        authorization-uri: https://nid.naver.com/oauth2.0/authorize
        token-uri: https://nid.naver.com/oauth2.0/token
        user-info-uri: https://openapi.naver.com/v1/nid/me
        user-name-attribute: response

      kakao:
        authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        user-name-attribute: id

service:
  jwt:
    secret-key: ENC(v2eS8Yl5nOs3cfQJhMtHQevpk7qHXEfxJYWhxrVzFgrCan6KORSlYSt7W+e2iV9L5uWDF6XHOwWtGNa3TUdHMQ==)
    access-expiration: 120000000 # millisecond
    refresh-expiration: 180000000

open-ai:
  url: https://api.openai.com/v1/chat/completions
  secret-key: ENC(cqRTCuBKQtrYRSz1UgmGfuhcZ/5swWX5K63FVCp4WiFHQDXdAn4wNDLPtR80LYD8QJctduN2EgUkTYA2UDkQ8g==)

cloud:
  aws:
    s3:
      bucket: ENC(zZThVC9CexDBRXjarD5F2Ox48hHHVG6249Or1yOhADA=)
    credentials:
      access-key: ENC(lAvvb3okmlD88vxNN7yxKbrL8LWyj+xVmW0jvYNaZAY=)
      secret-key: ENC(4f+JycMd/YH6vvpKMBCVvif5FjChn6kuEkFL7XOIX2EUqRZeAgMSKdGF0o9D0yf/yWQf78nqw80=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false