spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connectionTimeout: 5000
      validationTimeout: 1000
      maximumPoolSize: 10

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

oauth2:
  client:
    registration:
      google:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}
        authorization-grant-type: authorization_code
        scope: profile, email
        client-name: Google

      naver:
        client-id: ${NAVER_CLIENT_ID}
        client-secret: ${NAVER_CLIENT_SECRET}
        authorization-grant-type: authorization_code
        scope: name, email
        client-name: Naver

      kakao:
        client-id: ${KAKAO_CLIENT_ID}
        client-secret: ${KAKAO_CLIENT_SECRET}
        client-authentication-method: POST
        authorization-grant-type: authorization_code
        scope: profile_nickname, account_email
        client-name: Kakao

    provider:
      google:
        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
        token-uri: https://www.googleapis.com/oauth2/v4/token
        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
        user-name-attribute: sub

      naver:
        authorization-uri: https://nid.naver.com/oauth2.0/authorize
        token-uri: https://nid.naver.com/oauth2.0/token
        user-info-uri: https://openapi.naver.com/v1/nid/me
        user-name-attribute: response

      kakao:
        authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        user-name-attribute: id

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expiration: 6000000 # millisecond
    refresh-expiration: 180000000

open-ai:
  url: https://api.openai.com/v1/chat/completions
  secret-key: ${OPENAI_SECRET_KEY}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
